### ISSUE TITLE
Can you help change the font

### ISSUE THREAD

**Issue by Annnekkk** [sheodox/vrv-subtitler#51]
![image](https://github.com/sheodox/jimaku-player/assets/100362395/eedec989-ac21-4c06-a69f-5b546849bf12)
![image](https://github.com/sheodox/jimaku-player/assets/100362395/f0e0a00b-a0ae-4cc9-928d-f33ce5450467)
I'm using it to show my Vietnamese subtitile on Crunchryroll, but it font make subtitile look so funny. Or how can I add custom font for a better showing substiltle. Thank you so much

**Comment by sheodox** [comment]
Could you try downloading and installing the Noto Sans fonts and see if it looks better? https://fonts.google.com/noto/specimen/Noto+Sans

(you might need to restart your computer, i'm not sure).

**Comment by Annnekkk** [comment]
![image](https://github.com/sheodox/jimaku-player/assets/100362395/b66aff63-6ac1-4bd8-94cc-96e9a9ab59d6)
After I re-install Noto Sans fonts it look much more better, thank you so much.
